"""removed migration test column

Revision ID: 043e3acd8d6c
Revises: 9ef6cf8426f9
Create Date: 2026-06-19 16:52:01.967114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043e3acd8d6c'
down_revision: Union[str, Sequence[str], None] = '9ef6cf8426f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_column', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
